### ISSUE TITLE
UpdateCommand is not being imported from aws-sdk even though it is used

### ISSUE THREAD

**Issue by thisjt** [cyclic-software/session-store#11]
UpdateCommand is showing a parsing error as it is not being imported from aws-sdk.

https://github.com/cyclic-software/session-store/blob/f1c051929beac2861309448562ba64b064949a3b/src/CyclicSessionStore.js#L4
https://github.com/cyclic-software/session-store/blob/f1c051929beac2861309448562ba64b064949a3b/src/CyclicSessionStore.js#L211

Fix: https://github.com/thisjt/session-store/commit/3acaf78bfc8e9439f4d96cdabe367e582d01e291

**Comment by seekayel** [comment]
Thank you for the bug report and fix.

Can you create a pull request from that fix?

**Comment by thisjt** [comment]
Done. Please do review on it. Thanks! https://github.com/cyclic-software/session-store/pull/12

**Comment by seekayel** [comment]
Fixed and deployed
